[workspace]

members = ["project_core", "line_core", "cli_core", "scrapetoon", "tower-of-god", "true-beauty", "the-god-of-high-school", "lore-olympus", "unordinary", "kubera"]

[workspace.dependencies]
clap = {version = "4.0.25", features = ["derive"]}
reqwest = {version = "0.11.14", features = ["rustls", "blocking", "json"]}
scraper = "0.14.0"
csv = "1.1.6"
regex = "1.7.0"
tokio = { version = "1.21.2", features = ["full"] }
chrono = "0.4.23"
thirtyfour = "0.31.0"
static_assertions = "1.1.0"
rayon = "1.6.1"
indicatif = { version = "0.17.2", features = ["rayon"]}
image = "0.24.5"
rand = "0.8.5"
crossbeam = "0.8.2"
anyhow = { version = "1.0.68", features = ["backtrace"]}
pretty_assertions = "1.3.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
mockall = "0.11.2"