[workspace]

members = ["project_core", "line_core", "cli_core", "scrapetoon", "tower-of-god", "true-beauty", "the-god-of-high-school", "lore-olympus", "unordinary"]

[workspace.dependencies]
clap = {version = "4.0.25", features = ["derive"]}
scraper = "0.13.0"
csv = "1.1.6"
regex = "1.7.0"
tokio = { version = "1.21.2", features = ["full"] }
chrono = "0.4.23"
thirtyfour = "0.31.0"
static_assertions = "1.1.0"