[package]
name = "scrapetoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project_core = { path = "../project_core" }
line_core = { path = "../line_core" }
cli_core = { path = "../cli_core"}
csv = "1.1.6"
hashlink = "0.8.1"
clap = {version = "4.0.26", features = ["derive"]}
tokio = { version = "1.21.2", features = ["full"] }